project:
  type: website
  output-dir: _site

website:
  title: "Vision Language Models from Scratch"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Notebooks"
        menu:
          - text: "1. ViT Usage"
            href: vision-transformer-usage.ipynb
          - text: "2. Create Segmentation Dataset"
            href: create-segmentation-dataset.ipynb
          - text: "3. ViT Segmentation"
            href: vision-transformer-segmentation.ipynb
          - text: "4. ViT from Scratch"
            href: vision-transformer-scratch.ipynb
          - text: "5. Masked Dataset & Autoencoder"
            href: masked-dataset.ipynb
  page-footer:
    center: "Built with Quarto"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-tools: true
    code-copy: true
    number-sections: false
    anchor-sections: true
    smooth-scroll: true

execute:
  freeze: auto
  cache: false
